// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed horse.bob.sql
var formattedQueries_horse string

var getRelativeHorsesSQL = formattedQueries_horse[155:1767]

type GetRelativeHorsesQuery = orm.ModQuery[*dialect.SelectQuery, getRelativeHorses, GetRelativeHorsesRow, []GetRelativeHorsesRow, getRelativeHorsesTransformer]

func GetRelativeHorses(ID uuid.UUID) *GetRelativeHorsesQuery {
	var expressionTypArgs getRelativeHorses

	expressionTypArgs.ID = psql.Arg(ID)

	return &GetRelativeHorsesQuery{
		Query: orm.Query[getRelativeHorses, GetRelativeHorsesRow, []GetRelativeHorsesRow, getRelativeHorsesTransformer]{
			ExecQuery: orm.ExecQuery[getRelativeHorses]{
				BaseQuery: bob.BaseQuery[getRelativeHorses]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GetRelativeHorsesRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GetRelativeHorsesRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Herd)
						row.ScheduleScanByIndex(2, &t.Gender)
						row.ScheduleScanByIndex(3, &t.Name)
						row.ScheduleScanByIndex(4, &t.BirthDay)
						row.ScheduleScanByIndex(5, &t.BirthMonth)
						row.ScheduleScanByIndex(6, &t.BirthYear)
						row.ScheduleScanByIndex(7, &t.BirthPlace)
						row.ScheduleScanByIndex(8, &t.WithersHeight)
						row.ScheduleScanByIndex(9, &t.Sire)
						row.ScheduleScanByIndex(10, &t.Dam)
						row.ScheduleScanByIndex(11, &t.IsPregnant)
						row.ScheduleScanByIndex(12, &t.IsDead)
						row.ScheduleScanByIndex(13, &t.Description)
						row.ScheduleScanByIndex(14, &t.CreatedAt)
						row.ScheduleScanByIndex(15, &t.UpdatedAt)
						row.ScheduleScanByIndex(16, &t.VisitedIds)
						return &t, nil
					}, func(v any) (GetRelativeHorsesRow, error) {
						return *(v.(*GetRelativeHorsesRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.SetRecursive(true)
			q.AppendCTE(expressionTypArgs.subExpr(15, 926))
			q.AppendSelect(expressionTypArgs.subExpr(934, 1582))
			q.SetTable(expressionTypArgs.subExpr(1588, 1597))
			q.AppendWhere(expressionTypArgs.subExpr(1604, 1612))
		}),
	}
}

type GetRelativeHorsesRow = struct {
	ID            uuid.UUID           `db:"id"`
	Herd          uuid.UUID           `db:"herd"`
	Gender        null.Val[uuid.UUID] `db:"gender"`
	Name          null.Val[string]    `db:"name"`
	BirthDay      null.Val[int32]     `db:"birth_day"`
	BirthMonth    null.Val[int32]     `db:"birth_month"`
	BirthYear     null.Val[int32]     `db:"birth_year"`
	BirthPlace    null.Val[uuid.UUID] `db:"birth_place"`
	WithersHeight null.Val[int32]     `db:"withers_height"`
	Sire          null.Val[uuid.UUID] `db:"sire"`
	Dam           null.Val[uuid.UUID] `db:"dam"`
	IsPregnant    bool                `db:"is_pregnant"`
	IsDead        bool                `db:"is_dead"`
	Description   null.Val[string]    `db:"description"`
	CreatedAt     time.Time           `db:"created_at"`
	UpdatedAt     time.Time           `db:"updated_at"`
	VisitedIds    pq.StringArray      `db:"visited_ids"`
}

type getRelativeHorsesTransformer = bob.SliceTransformer[GetRelativeHorsesRow, []GetRelativeHorsesRow]

type getRelativeHorses struct {
	ID bob.Expression
}

func (o getRelativeHorses) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "id",
			Start:      605,
			Stop:       607,
			Expression: o.ID,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "id",
			Start:      1610,
			Stop:       1612,
			Expression: o.ID,
		}) {
			return
		}
	}
}

func (o getRelativeHorses) raw(from, to int) string {
	return getRelativeHorsesSQL[from:to]
}

func (o getRelativeHorses) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(getRelativeHorsesSQL, from, to, o.args())
}

func (o getRelativeHorses) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(getRelativeHorsesSQL)).WriteSQL(ctx, w, d, start)
}
