// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	testutils "github.com/stephenafamo/bob/test/utils"
)

func TestGetRelativeHorses(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := GetRelativeHorses(random_uuid_UUID(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(getRelativeHorsesSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := GetRelativeHorses(random_uuid_UUID(nil))

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(getRelativeHorsesSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		query, args, err := bob.Build(ctxTx, psql.Select(GetRelativeHorses(random_uuid_UUID(nil))))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer rows.Close()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 17 {
			t.Fatalf("expected %d columns, got %d", 17, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "herd" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "herd", columns[1])
		}

		if columns[2] != "gender" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "gender", columns[2])
		}

		if columns[3] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "name", columns[3])
		}

		if columns[4] != "birth_day" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "birth_day", columns[4])
		}

		if columns[5] != "birth_month" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "birth_month", columns[5])
		}

		if columns[6] != "birth_year" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "birth_year", columns[6])
		}

		if columns[7] != "birth_place" {
			t.Fatalf("expected column %d to be %s, got %s", 7, "birth_place", columns[7])
		}

		if columns[8] != "withers_height" {
			t.Fatalf("expected column %d to be %s, got %s", 8, "withers_height", columns[8])
		}

		if columns[9] != "sire" {
			t.Fatalf("expected column %d to be %s, got %s", 9, "sire", columns[9])
		}

		if columns[10] != "dam" {
			t.Fatalf("expected column %d to be %s, got %s", 10, "dam", columns[10])
		}

		if columns[11] != "is_pregnant" {
			t.Fatalf("expected column %d to be %s, got %s", 11, "is_pregnant", columns[11])
		}

		if columns[12] != "is_dead" {
			t.Fatalf("expected column %d to be %s, got %s", 12, "is_dead", columns[12])
		}

		if columns[13] != "description" {
			t.Fatalf("expected column %d to be %s, got %s", 13, "description", columns[13])
		}

		if columns[14] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 14, "created_at", columns[14])
		}

		if columns[15] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 15, "updated_at", columns[15])
		}

		if columns[16] != "visited_ids" {
			t.Fatalf("expected column %d to be %s, got %s", 16, "visited_ids", columns[16])
		}
	})
}
