-- Code generated by BobGen psql v0.42.0. DO NOT EDIT.
-- This file is meant to be re-generated in place and/or deleted at any time.

-- GetRelativeHorses
WITH RECURSIVE relatives AS (
        SELECT
        "h"."id" AS "id", "h"."herd" AS "herd", "h"."gender" AS "gender", "h"."name" AS "name", "h"."birth_day" AS "birth_day", "h"."birth_month" AS "birth_month", "h"."birth_year" AS "birth_year", "h"."birth_place" AS "birth_place", "h"."withers_height" AS "withers_height", "h"."sire" AS "sire", "h"."dam" AS "dam", "h"."is_pregnant" AS "is_pregnant", "h"."is_dead" AS "is_dead", "h"."description" AS "description", "h"."created_at" AS "created_at", "h"."updated_at" AS "updated_at",
        ARRAY[h.id] AS visited_ids
    FROM app.horses h
    WHERE h.id = $1

    UNION ALL

        SELECT
        h.*,
        r.visited_ids || h.id
    FROM app.horses h
             JOIN relatives r
                  ON h.id = r.sire
                      OR h.id = r.dam
                      OR h.sire = r.id
                      OR h.dam = r.id
    WHERE NOT h.id = ANY (r.visited_ids)
)
SELECT "relatives"."id" AS "id", "relatives"."herd" AS "herd", "relatives"."gender" AS "gender", "relatives"."name" AS "name", "relatives"."birth_day" AS "birth_day", "relatives"."birth_month" AS "birth_month", "relatives"."birth_year" AS "birth_year", "relatives"."birth_place" AS "birth_place", "relatives"."withers_height" AS "withers_height", "relatives"."sire" AS "sire", "relatives"."dam" AS "dam", "relatives"."is_pregnant" AS "is_pregnant", "relatives"."is_dead" AS "is_dead", "relatives"."description" AS "description", "relatives"."created_at" AS "created_at", "relatives"."updated_at" AS "updated_at", "relatives"."visited_ids" AS "visited_ids"
FROM relatives
WHERE id <> $2;
