// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package repository

import (
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	pg_query "github.com/wasilibs/go-pgquery"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

func formatQuery(s string) (string, error) {
	aTree, err := pg_query.Parse(s)
	if err != nil {
		return "", err
	}

	return pg_query.Deparse(aTree)
}

var defaultFaker = faker.New()

func random_bool(f *faker.Faker, limits ...string) bool {
	if f == nil {
		f = &defaultFaker
	}

	return f.Bool()
}

func random_int32(f *faker.Faker, limits ...string) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_pq_StringArray(f *faker.Faker, limits ...string) pq.StringArray {
	if f == nil {
		f = &defaultFaker
	}

	arr := make(pq.StringArray, f.IntBetween(1, 5))
	for i := range arr {
		arr[i] = random_string(f, limits...)
	}
	return arr
}

func random_string(f *faker.Faker, limits ...string) string {
	if f == nil {
		f = &defaultFaker
	}

	val := strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
	if len(limits) == 0 {
		return val
	}
	limitInt, _ := strconv.Atoi(limits[0])
	if limitInt > 0 && limitInt < len(val) {
		val = val[:limitInt]
	}
	return val
}

func random_time_Time(f *faker.Faker, limits ...string) time.Time {
	if f == nil {
		f = &defaultFaker
	}

	year := time.Hour * 24 * 365
	min := time.Now().Add(-year)
	max := time.Now().Add(year)
	return f.Time().TimeBetween(min, max)
}

func random_uuid_UUID(f *faker.Faker, limits ...string) uuid.UUID {
	if f == nil {
		f = &defaultFaker
	}

	return uuid.New()
}
